-- Add new FieldType enum values
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'INITIALS';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'NUMBER';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'CHECKBOX';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'RADIO';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'SELECT';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'FILE';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'STAMP';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE "FieldType" ADD VALUE IF NOT EXISTS 'CELLS';

-- Add signerId (field assignment to specific signer)
ALTER TABLE "DocumentField" ADD COLUMN IF NOT EXISTS "signerId" TEXT;
ALTER TABLE "DocumentField" ADD CONSTRAINT "DocumentField_signerId_fkey"
  FOREIGN KEY ("signerId") REFERENCES "Signer"("id") ON DELETE SET NULL;

-- Add options array for SELECT / RADIO / CHECKBOX
ALTER TABLE "DocumentField" ADD COLUMN IF NOT EXISTS "options" TEXT[] NOT NULL DEFAULT '{}';

-- Add groupId for grouping RADIO / CHECKBOX fields
ALTER TABLE "DocumentField" ADD COLUMN IF NOT EXISTS "groupId" TEXT;
